version: '3.3'

services:
  server:
    image: hammer/frevocrm:latest
    ports: 
      - 8087:80
    restart: always
    deploy:
      mode: replicated
      replicas: 1 
    networks:
      - attachable

networks:
  attachable:
    external: true

