version: '3.3'

services:
  server:
    image: hammer/frevocrm:latest
    ports: 
      - 8087:80
    depends_on:
      - db
    restart: always
    deploy:
      mode: replicated
      replicas: 1 

  db:
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frevocrm
      MYSQL_USER: docker
      MYSQL_PASSWORD: my-secret-pw
    restart: always
    configs:
      - source:  frevocrm-db
        target: /etc/mysql/conf.d/frevo.cnf
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

configs:
  frevocrm-db:
    external: true

